import Groq from 'groq-sdk';
import dotenv from 'dotenv';
dotenv.config();

const rawKey = process.env.GROQ_API_KEY || '';
const apiKey = rawKey.trim();
const ai = apiKey ? new Groq({ apiKey }) : null;

/**
 * Generate a code patch using Groq API.
 * Falls back to a simulated patch if no API key is configured.
 */
export async function generateCodePatch(brokenCode, errorMessage, language = 'Auto', customInstructions = '') {
  if (!ai) {
    console.warn('⚠️ GROQ_API_KEY not found in .env. Returning simulated patch.');
    return {
      code: getSimulatedPatch(language, brokenCode),
      explanation: 'Simulated patch (no API key configured). Add GROQ_API_KEY to .env for real AI fixes.',
      tokens: { prompt: 0, completion: 0, total: 0 },
    };
  }

  try {
    const prompt = `You are the Lead Code Repair Agent. Analyze and fix this broken ${language} code.

USER'S CUSTOM SYSTEM INSTRUCTIONS (Follow these strictly!):
${customInstructions ? customInstructions : "No custom instructions. Write clean, standard code."}

Error / Stack Trace:
${errorMessage || 'None provided.'}

Broken Code:
${brokenCode}

Instructions:
1. Identify the root cause of the error and fix it.
2. Analyze the dependencies of this code (e.g., what services, databases, or external modules it uses).
3. Return a JSON object with EXACTLY the following structure:
{
  "code": "The full corrected, executable code here (use \\n for newlines, do not wrap in markdown code blocks)",
  "explanation": "A short 1-sentence explanation of what was fixed",
  "nodes": [
    { "id": "1", "label": "MainClassName (Target)", "status": "PATCHED", "type": "primary" },
    { "id": "2", "label": "SomeDependency", "status": "OK", "type": "dependency" }
  ],
  "securitySuggestions": [
    {
      "title": "SQL Injection Risk",
      "severity": "critical",
      "description": "User input is directly concatenated into the query.",
      "fix": "Use parameterized queries or an ORM."
    }
  ],
  "testOutput": [
    { "type": "header", "text": "PASS tests/AutoGenerated.test" },
    { "type": "pass", "text": "  ✓ SHOULD handle edge cases gracefully" },
    { "type": "pass", "text": "  ✓ SHOULD execute main logic without errors" },
    { "type": "summary", "text": "Test Suites: 1 passed, 1 total" }
  ]
}
Make sure "nodes" includes at least 2 or 3 meaningful dependencies you detect in the code.
Make sure "securitySuggestions" includes any real vulnerabilities you found and how you fixed them (or return an empty array if the code is perfectly secure).
Make sure "testOutput" includes realistic mock unit test logs that prove your code works.
Respond ONLY with raw valid JSON. Do not include markdown formatting (like \`\`\`json) at the beginning or end.`;

    const response = await ai.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.1-8b-instant',
      max_tokens: 950,
    });

    const rawText = response.choices[0]?.message?.content || '{}';

    // Extract JSON block by finding first { and last }
    let cleanedJsonText = rawText;
    const firstBrace = cleanedJsonText.indexOf('{');
    const lastBrace = cleanedJsonText.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace >= firstBrace) {
      cleanedJsonText = cleanedJsonText.substring(firstBrace, lastBrace + 1);
    } else {
      cleanedJsonText = rawText.replace(/^```[\w]*\n?/gm, '').replace(/```$/gm, '').trim();
    }

    let parsedData = {};
    try {
      parsedData = JSON.parse(cleanedJsonText);
    } catch (e) {
      console.error("Failed to parse JSON from LLM (likely truncated). Attempting regex extraction.");

      // If JSON is truncated, try to manually extract the "code" field value using Regex
      let extractedCode = cleanedJsonText;
      const codeMatch = cleanedJsonText.match(/"code"\s*:\s*"([\s\S]*?)(?:"|$)/);
      if (codeMatch && codeMatch[1]) {
        // Unescape newlines and quotes
        extractedCode = codeMatch[1].replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
      }

      parsedData = {
        code: extractedCode,
        explanation: 'Patch generated (JSON parsing failed due to length).',
        nodes: []
      };
    }

    const tokens = response.usage
      ? {
        prompt: response.usage.prompt_tokens || 0,
        completion: response.usage.completion_tokens || 0,
        total: response.usage.total_tokens || 0,
      }
      : { prompt: 0, completion: 0, total: 0 };

    return {
      code: parsedData.code || '',
      explanation: parsedData.explanation || 'Patch generated.',
      nodes: parsedData.nodes || [],
      securitySuggestions: parsedData.securitySuggestions || [],
      testOutput: parsedData.testOutput || [],
      tokens
    };
  } catch (err) {
    console.error('Groq API Call Failed:', err.message);
    throw err;
  }
}

/**
 * Simulated fallback patches when no API key is available
 */
function getSimulatedPatch(language, input) {
  const lang = (language || '').toLowerCase();

  if (lang.includes('rust') || input.includes('.rs')) {
    return `// main.rs - PATCHED by AI Agent\n// Fix: Safely match on Option to prevent panic on None value\n\nfn get_user_bio(user: Option<&User>) -> String {\n    match user {\n        Some(u) => u.profile.bio.clone(),\n        None => String::from(""),\n    }\n}`;
  }
  if (lang.includes('python') || input.includes('.py')) {
    return `# analytics.py - PATCHED by AI Agent\n# Fix: Safe dictionary key lookup with fallback\n\ndef get_value(d):\n    if not isinstance(d, dict):\n        return 'dark'\n    return d.get('settings', {}).get('theme', 'dark')`;
  }
  if (lang.includes('c++') || lang.includes('cpp') || input.includes('.cpp')) {
    return `// vector_bounds.cpp - PATCHED by AI Agent\n// Fix: Vector index bounds check\n\n#include <vector>\n\nint get_item(const std::vector<int>& v, size_t i) {\n    if (i >= v.size()) {\n        return -1; // Safe fallback guard\n    }\n    return v[i];\n}`;
  }
  if (lang.includes('node') || lang.includes('javascript') || lang.includes('js') || input.includes('.js')) {
    return `// userController.js - PATCHED by AI Agent\n// Fix: Safe property navigation with optional chaining\n\nfunction getEmail(user) {\n    if (!user || !user.contact) {\n        return '';\n    }\n    return user?.contact?.email ?? '';\n}`;
  }
  // Default: Golang
  return `// user_handler.go - PATCHED by AI Agent\n// Fix: Defensive nil pointer guard\npackage main\n\nfunc GetUserBio(u *User) string {\n    if u == nil || u.Profile == nil {\n        return ""\n    }\n    return u.Profile.Bio\n}`;
}
