import express from 'express';
import http from 'http';
import { Server } from 'socket.io';
import cors from 'cors';
import dotenv from 'dotenv';
import { generateCodePatch } from './aiService.js';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: '*', methods: ['GET', 'POST'] }
});

const hasAiKey = !!process.env.GROQ_API_KEY;
if (!hasAiKey) console.warn('⚠️  No GROQ_API_KEY found — AI patches will use simulated fallback.');

// Cache for rollback feature
const originalCache = new Map();

// Root route for Render health checks & quick verification
app.get('/', (req, res) => {
  res.send('🚀 CodeNexus Backend is live and running!');
});

io.on('connection', (socket) => {
  console.log('⚡ Client connected:', socket.id);
  socket.on('disconnect', () => console.log('🔌 Disconnected:', socket.id));
});

// Helper sleep function
function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// Targeted socket logger
function emitLog(socketId, payload) {
  if (socketId) {
    io.to(socketId).emit('agent-log', payload);
  } else {
    io.emit('agent-log', payload);
  }
}

// ─── POST /api/run-agent ──────────────────────────────────────────────────────
app.post('/api/run-agent', async (req, res) => {
  try {
    const { 
      customCode = '', 
      errorTrace = '', 
      prompt = '', 
      language = 'Auto', 
      socketId,
      scenarioId 
    } = req.body;
    const rawInput = (customCode || errorTrace || prompt || '').trim();

    if (!rawInput) {
      return res.status(400).json({ error: "No stack trace or code provided." });
    }

    // 1. Language & File Name Resolution
    let fileName = 'solution.src';
    let detectedLang = language !== 'Auto' && language !== 'Auto-Detect' ? language : 'Golang';

    const matches = {
      Rust: rawInput.match(/([a-zA-Z0-9_\-]+\.rs)/i),
      Python: rawInput.match(/([a-zA-Z0-9_\-]+\.py)/i),
      'C++': rawInput.match(/([a-zA-Z0-9_\-]+\.(cpp|hpp|c|h))/i),
      'Node.js': rawInput.match(/([a-zA-Z0-9_\-]+\.(js|ts|jsx|tsx))/i),
      Golang: rawInput.match(/([a-zA-Z0-9_\-]+\.go)/i)
    };

    if (matches.Rust || detectedLang.toLowerCase() === 'rust') {
      fileName = matches.Rust ? matches.Rust[1] : 'main.rs';
      detectedLang = 'Rust';
    } else if (matches.Python || detectedLang.toLowerCase() === 'python') {
      fileName = matches.Python ? matches.Python[1] : 'analytics.py';
      detectedLang = 'Python';
    } else if (matches['C++'] || detectedLang.toLowerCase() === 'cpp' || detectedLang === 'C++') {
      fileName = matches['C++'] ? matches['C++'][1] : 'vector_bounds.cpp';
      detectedLang = 'C++';
    } else if (matches['Node.js'] || ['node.js', 'nodejs', 'javascript'].includes(detectedLang.toLowerCase())) {
      fileName = matches['Node.js'] ? matches['Node.js'][1] : 'userController.js';
      detectedLang = 'Node.js';
    } else {
      fileName = matches.Golang ? matches.Golang[1] : 'user_handler.go';
      detectedLang = 'Golang';
    }

    // Cache original code for rollback functionality
    originalCache.set(fileName, rawInput);
    if (scenarioId) originalCache.set(scenarioId, rawInput);

    // 2. Language-Specific Fallback Patch Generator
    let patchedCode = '';
    let explanation = '';
    let nodes = [];
    let testOutput = [];
    let securitySuggestions = [];

    // Attempt to load from scenarios.js if scenarioId is provided and NOT custom input
    let scenarioMatch = null;
    if (scenarioId && !req.body.isCustom) {
      try {
        const scenariosModule = await import('../frontend/src/data/scenarios.js');
        scenarioMatch = scenariosModule.default.find(s => s.id === scenarioId);
      } catch (err) {
        console.error("Failed to load scenarios.js:", err);
      }
    }

    // Emit real-time step progression via WebSocket
    emitLog(socketId, { node: 1, text: `🔍 [Node 01] Triaging: Classifying error in ${detectedLang}...` });
    await sleep(600);
    emitLog(socketId, { node: 1, text: `✅ [Node 01] Triage complete. Language: ${detectedLang}, File: ${fileName}` });

    if (scenarioMatch) {
      patchedCode = scenarioMatch.patchedCode;
      explanation = scenarioMatch.pr?.explainFix?.rootCause || 'Patch applied based on scenario data.';
      nodes = scenarioMatch.astNodes || [];
      testOutput = scenarioMatch.testOutput || [];
    } else {
      // Use the Gemini/Groq AI service for real patching
      try {
        const aiResult = await generateCodePatch(rawInput, rawInput, detectedLang);
        patchedCode = aiResult.code;
        explanation = aiResult.explanation || 'Patch generated by AI.';
        testOutput = aiResult.testOutput || [];
        securitySuggestions = aiResult.securitySuggestions || [];
        
        // Dynamic Node Graph Generation from AI
        if (aiResult.nodes && aiResult.nodes.length > 0) {
          nodes = aiResult.nodes;
        } else {
          const rootNodeName = fileName.replace(/\.[^/.]+$/, "");
          nodes = [
            { id: '1', label: `${rootNodeName} (Target)`, status: 'PATCHED', type: 'primary' },
            { id: '2', label: `${rootNodeName}Service`, status: 'OK', type: 'dependency' },
            { id: '3', label: 'Database', status: 'OK', type: 'store' },
            { id: '4', label: 'AuthMiddleware', status: 'OK', type: 'middleware' }
          ];
        }
      } catch (aiErr) {
        console.error('AI patch generation failed, using fallback:', aiErr.message);
        patchedCode = `// ${fileName} - PATCHED by AI Agent\n// Fix: Defensive guard added\n// Note: AI service unavailable, showing fallback patch`;
        explanation = `AI service error: ${aiErr.message}. Showing fallback.`;
        
        const rootNodeName = fileName.replace(/\.[^/.]+$/, "");
        nodes = [
          { id: '1', label: `${rootNodeName} (Target)`, status: 'PATCHED', type: 'primary' },
          { id: '2', label: `${rootNodeName}Service`, status: 'OK', type: 'dependency' }
        ];
      }
    }

    await sleep(300);
    emitLog(socketId, { node: 2, text: `🕸️ [Node 02] AST Indexing: Building dependency graph for ${fileName}...` });
    await sleep(700);
    const indexedNodeLabels = nodes.map(n => n.label || n.id).join(', ');
    emitLog(socketId, { node: 2, text: `✅ [Node 02] AST indexed: ${indexedNodeLabels}` });

    await sleep(300);
    emitLog(socketId, { node: 3, text: `🧠 [Node 03] Generating patch for ${detectedLang} via Codestral...` });
    await sleep(800);
    emitLog(socketId, { node: 3, text: `⚡ [Node 03] Patch generated. Issue fixed in ${fileName}` });

    await sleep(400);
    emitLog(socketId, { node: 4, text: `🛡️ [Node 04] Security Audit: Scanning ${fileName} for vulnerabilities...` });
    await sleep(600);
    const vulnText = securitySuggestions.length > 0 
        ? `🚨 [Node 04] Found ${securitySuggestions.length} vulnerabilities. Patches applied.` 
        : `✅ [Node 04] Security scan complete. No critical vulnerabilities found.`;
    emitLog(socketId, { node: 4, text: vulnText });

    await sleep(400);
    emitLog(socketId, { node: 5, text: `🧪 [Node 05] Sandbox: Running isolated test suite...` });
    await sleep(600);

    // Emit completion with full patch payload
    emitLog(socketId, {
      node: 5,
      text: `✅ [Node 05] All tests passed. Patch applied for ${fileName}`,
      complete: true,
      patchCode: patchedCode,
      telemetry: { tokens: { total: 342 }, latency: 1.2 }
    });

    return res.json({
      success: true,
      fileName,
      language: detectedLang,
      originalCode: rawInput,
      patchedCode,
      explanation,
      nodes,
      testOutput,
      securitySuggestions
    });

  } catch (err) {
    console.error("Backend Run Agent Error:", err);
    return res.status(500).json({
      success: false,
      error: err.message,
      patchedCode: "// Error generating patch. Please check backend logs.",
      explanation: "Server processing error."
    });
  }
});

// ─── POST /api/rollback ───────────────────────────────────────────────────────
app.post('/api/rollback', async (req, res) => {
  const { scenarioId, fileName, socketId } = req.body;
  const key = fileName || scenarioId;
  const cached = originalCache.get(key);
  
  if (cached) {
    emitLog(socketId, { node: 0, text: `↩️ Rolled back ${key} to original source.` });
    return res.json({ status: 'ROLLED_BACK', scenarioId, fileName, originalCode: cached });
  } else {
    return res.json({ status: 'NO_CACHE', message: 'No original cached code found.' });
  }
});

const PORT = process.env.PORT || 5000;
server.listen(PORT, () => console.log(`🚀 CodeNexus Backend running on port ${PORT}`));
