import React from 'react';
import { motion } from 'framer-motion';
import { X, FileText, CheckCircle2, ShieldAlert, Cpu } from 'lucide-react';

export default function ReportModal({ activeRun, onClose }) {
  if (!activeRun) return null;

  const handlePrint = () => window.print();

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0a0a0a]/80 backdrop-blur-sm p-4 print:bg-white print:p-0">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        className="w-full max-w-3xl max-h-full overflow-y-auto bg-[#111111] border border-slate-700 rounded-2xl shadow-2xl print:bg-white print:text-black print:border-none print:shadow-none"
      >
        <div className="sticky top-0 bg-[#111111]/90 backdrop-blur border-b border-slate-800 p-4 flex items-center justify-between print:hidden">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h2 className="text-sm font-bold text-slate-100 uppercase tracking-widest">Post-Mortem Incident Report</h2>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handlePrint} className="px-4 py-1.5 bg-cyan-600/20 text-cyan-400 border border-cyan-500/30 rounded-lg text-xs font-bold hover:bg-cyan-600/30 transition-colors">
              Export PDF
            </button>
            <button onClick={onClose} className="p-1.5 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-slate-200 transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="p-8 space-y-8 print:p-8">
          {/* Header */}
          <div className="border-b border-slate-800 pb-6 print:border-gray-300">
            <div className="flex items-center gap-3 mb-4">
              <Cpu className="w-8 h-8 text-cyan-500 print:text-gray-800" />
              <div>
                <h1 className="text-2xl font-black text-slate-100 tracking-tight print:text-black">The Window AI Patch Report</h1>
                <div className="text-xs font-mono text-slate-500 print:text-gray-500">Auto-Generated by Autonomous Agent</div>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4 text-xs font-mono">
              <div className="text-slate-400 print:text-gray-600">File: <span className="text-slate-200 print:text-black">{activeRun.fileName}</span></div>
              <div className="text-slate-400 print:text-gray-600">Language: <span className="text-slate-200 print:text-black">{activeRun.language}</span></div>
              <div className="text-slate-400 print:text-gray-600">Status: <span className="text-emerald-400 print:text-green-600 font-bold">PATCHED & VERIFIED</span></div>
              <div className="text-slate-400 print:text-gray-600">Date: <span className="text-slate-200 print:text-black">{new Date().toLocaleString()}</span></div>
            </div>
          </div>

          {/* What it was */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-sm font-bold text-slate-100 uppercase tracking-widest border-b border-slate-800/50 pb-2 print:text-black print:border-gray-300">
              <span className="text-red-400 print:text-red-600">01</span> What it was (The Bug)
            </div>
            <p className="text-sm text-slate-300 leading-relaxed print:text-gray-700">
              The original implementation contained critical flaws that caused runtime errors or security vulnerabilities. Below is the active stack trace and original snippet:
            </p>
            <pre className="p-4 bg-[#0a0a0a] border border-slate-800 rounded-xl text-xs font-mono text-red-300 overflow-x-auto print:bg-gray-100 print:border-gray-300 print:text-red-800">
              <code>{activeRun.originalCode}</code>
            </pre>
          </section>

          {/* What we did */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-sm font-bold text-slate-100 uppercase tracking-widest border-b border-slate-800/50 pb-2 print:text-black print:border-gray-300">
              <span className="text-emerald-400 print:text-green-600">02</span> What we did (The Fix)
            </div>
            <p className="text-sm text-slate-300 leading-relaxed print:text-gray-700">
              {activeRun.explanation}
            </p>
            <pre className="p-4 bg-[#0a0a0a] border border-slate-800 rounded-xl text-xs font-mono text-emerald-300 overflow-x-auto print:bg-gray-100 print:border-gray-300 print:text-green-800">
              <code>{activeRun.patchedCode}</code>
            </pre>
          </section>

          {/* What we recommend */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-sm font-bold text-slate-100 uppercase tracking-widest border-b border-slate-800/50 pb-2 print:text-black print:border-gray-300">
              <span className="text-purple-400 print:text-purple-600">03</span> What we recommend (Security)
            </div>
            {activeRun.securitySuggestions && activeRun.securitySuggestions.length > 0 ? (
              <div className="grid gap-3">
                {activeRun.securitySuggestions.map((s, i) => (
                  <div key={i} className="p-4 bg-purple-950/20 border border-purple-500/20 rounded-xl print:bg-white print:border-gray-300">
                    <div className="flex items-center gap-2 mb-2">
                      <ShieldAlert className="w-4 h-4 text-purple-400 print:text-purple-600" />
                      <h4 className="text-sm font-bold text-purple-300 print:text-purple-800">{s.title}</h4>
                      <span className="text-[9px] uppercase px-2 py-0.5 rounded-full border border-purple-500/30 text-purple-400 print:border-purple-600 print:text-purple-600">{s.severity}</span>
                    </div>
                    <p className="text-xs text-slate-300 mb-2 print:text-gray-700">{s.description}</p>
                    <div className="text-xs font-mono text-emerald-400 flex items-center gap-1.5 print:text-green-700">
                      <CheckCircle2 className="w-3 h-3" /> Recommended Fix: {s.fix}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-emerald-400 flex items-center gap-2 print:text-green-700">
                <CheckCircle2 className="w-4 h-4" /> No additional critical vulnerabilities detected. Standard best practices apply.
              </p>
            )}
          </section>

        </div>
      </motion.div>
    </div>
  );
}
